language: ruby
sudo: false
dist: trusty
rvm:
- 2.2
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
script:
  - gem install bundler
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
  on:
    branch: master
